/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypet;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author kfard
 */
public class petRegistration extends javax.swing.JFrame {

    /**
     * Creates new form petRegistration
     */
    public petRegistration() {
        initComponents();
    }
    void addPet(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection conn = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-OECCDJF\\SQLEXPRESS;databaseName=MYPET","sa","alphacoders4T4");
            Statement stmt = conn.createStatement();
            String qrry;
            qrry = "INSERT INTO PETINFO VALUES("+"'"+PET_NAME.getText()+"'"+","+"'"+PET_TYPE.getText()+"'"+","+"'"+DATE_OF_BRITH.getText()+"'"+","+"'"+PET_BREED.getText()+"'"+","+"'"+GENDER.getText()+"'"+","+"'"+COLOUR.getText()+"'"+","+"'"+WEIGHT.getText()+"'"+","+"'"+AGE.getText()+"'"+","+"'"+PET_PURSE_DATE.getText()+"'"+","+"'"+PURSE_FROM.getText()+"'"+");";
            boolean gotResults=stmt.execute(qrry);
            ResultSet rs = null;
            if(!gotResults){
                System.out.println("No results returned");
            }
            else {
                rs = stmt.getResultSet();
                }
            
            JOptionPane.showMessageDialog(rootPane,"NEW PET ADDED");
            
        }catch(ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(rootPane,ex);
        }
        PET_NAME.setText(null);
        PET_TYPE.setText(null);
        DATE_OF_BRITH.setText(null);
        PET_BREED.setText(null);
        GENDER.setText(null);
        COLOUR.setText(null);
        WEIGHT.setText(null);
        AGE.setText(null);
        PET_PURSE_DATE.setText(null);
        PURSE_FROM.setText(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PET_TYPE = new javax.swing.JTextField();
        DATE_OF_BRITH = new javax.swing.JTextField();
        PET_NAME = new javax.swing.JTextField();
        PET_BREED = new javax.swing.JTextField();
        COLOUR = new javax.swing.JTextField();
        GENDER = new javax.swing.JTextField();
        PURSE_FROM = new javax.swing.JTextField();
        PET_PURSE_DATE = new javax.swing.JTextField();
        WEIGHT = new javax.swing.JTextField();
        AGE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NEW PET", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tekton Pro", 1, 13))); // NOI18N

        PET_TYPE.setBackground(new java.awt.Color(204, 204, 204));
        PET_TYPE.setBorder(javax.swing.BorderFactory.createTitledBorder("PET TYPE"));
        PET_TYPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PET_TYPEActionPerformed(evt);
            }
        });

        DATE_OF_BRITH.setBackground(new java.awt.Color(204, 204, 204));
        DATE_OF_BRITH.setBorder(javax.swing.BorderFactory.createTitledBorder("DATE OF BRITH"));
        DATE_OF_BRITH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATE_OF_BRITHActionPerformed(evt);
            }
        });

        PET_NAME.setBackground(new java.awt.Color(204, 204, 204));
        PET_NAME.setBorder(javax.swing.BorderFactory.createTitledBorder("PET NAME"));
        PET_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PET_NAMEActionPerformed(evt);
            }
        });

        PET_BREED.setBackground(new java.awt.Color(204, 204, 204));
        PET_BREED.setBorder(javax.swing.BorderFactory.createTitledBorder("PET BREED"));
        PET_BREED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PET_BREEDActionPerformed(evt);
            }
        });

        COLOUR.setBackground(new java.awt.Color(204, 204, 204));
        COLOUR.setBorder(javax.swing.BorderFactory.createTitledBorder("COLOUR"));
        COLOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COLOURActionPerformed(evt);
            }
        });

        GENDER.setBackground(new java.awt.Color(204, 204, 204));
        GENDER.setBorder(javax.swing.BorderFactory.createTitledBorder("GENDER"));
        GENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GENDERActionPerformed(evt);
            }
        });

        PURSE_FROM.setBackground(new java.awt.Color(204, 204, 204));
        PURSE_FROM.setBorder(javax.swing.BorderFactory.createTitledBorder("PURSE FROM"));
        PURSE_FROM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PURSE_FROMActionPerformed(evt);
            }
        });

        PET_PURSE_DATE.setBackground(new java.awt.Color(204, 204, 204));
        PET_PURSE_DATE.setBorder(javax.swing.BorderFactory.createTitledBorder("PET PURSE DATE"));
        PET_PURSE_DATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PET_PURSE_DATEActionPerformed(evt);
            }
        });

        WEIGHT.setBackground(new java.awt.Color(204, 204, 204));
        WEIGHT.setBorder(javax.swing.BorderFactory.createTitledBorder("WEIGHT"));
        WEIGHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WEIGHTActionPerformed(evt);
            }
        });

        AGE.setBackground(new java.awt.Color(204, 204, 204));
        AGE.setBorder(javax.swing.BorderFactory.createTitledBorder("AGE"));
        AGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGEActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("ADD PET");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WEIGHT, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PET_PURSE_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PURSE_FROM, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DATE_OF_BRITH, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PET_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(COLOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PET_TYPE, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PET_BREED, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(354, 354, 354))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PET_TYPE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(PET_BREED, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PET_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(DATE_OF_BRITH, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COLOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GENDER, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AGE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(WEIGHT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PURSE_FROM, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PET_PURSE_DATE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PET_TYPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PET_TYPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PET_TYPEActionPerformed

    private void DATE_OF_BRITHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATE_OF_BRITHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DATE_OF_BRITHActionPerformed

    private void PET_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PET_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PET_NAMEActionPerformed

    private void PET_BREEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PET_BREEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PET_BREEDActionPerformed

    private void COLOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COLOURActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COLOURActionPerformed

    private void GENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GENDERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GENDERActionPerformed

    private void PURSE_FROMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PURSE_FROMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PURSE_FROMActionPerformed

    private void PET_PURSE_DATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PET_PURSE_DATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PET_PURSE_DATEActionPerformed

    private void WEIGHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WEIGHTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WEIGHTActionPerformed

    private void AGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addPet();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(petRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(petRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(petRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(petRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new petRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AGE;
    private javax.swing.JTextField COLOUR;
    private javax.swing.JTextField DATE_OF_BRITH;
    private javax.swing.JTextField GENDER;
    private javax.swing.JTextField PET_BREED;
    private javax.swing.JTextField PET_NAME;
    private javax.swing.JTextField PET_PURSE_DATE;
    private javax.swing.JTextField PET_TYPE;
    private javax.swing.JTextField PURSE_FROM;
    private javax.swing.JTextField WEIGHT;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
